// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: feeds.sql

package database

import (
	"context"
	"database/sql"
)

const createFeed = `-- name: CreateFeed :one
INSERT INTO feeds (name, url)
VALUES ($1, $2)
RETURNING name, url
`

type CreateFeedParams struct {
	Name sql.NullString
	Url  sql.NullString
}

func (q *Queries) CreateFeed(ctx context.Context, arg CreateFeedParams) (Feed, error) {
	row := q.db.QueryRowContext(ctx, createFeed, arg.Name, arg.Url)
	var i Feed
	err := row.Scan(&i.Name, &i.Url)
	return i, err
}
